### ISSUE TITLE
Still can't fetch lib aar/jar from mvn repo by gradle

### ISSUE THREAD

**Issue by ghost** [Xiaofei-it/Hermes-EventBus#2]
Have you uploaded them to repo? If not when will upload them to?

**Comment by Xiaofei-it** [comment]
I have uploaded the library to jCenter. If you use Android Studio, you can fetch the library by Gradle.
May I know what IDE you use? Do you use Maven Central?
And I will upload the library to Maven Central as soon as possible.

**Comment by ghost** [comment]
After I changed my gradle(IDEA 15 CE) repo to jcenter, it works. 
If possible please update this info to project readme page or somewhere. 
Did I miss something? I recheck and didn't find this information.
