### ISSUE TITLE
I cannot continuous connect service and application

### ISSUE THREAD

**Issue by NikolayMakhonin** [Xiaofei-it/Hermes-EventBus#3]
I tried many possible variants. When the application is restarted, the connection to the service is interrupted or HermesEventBus throwing error.
I need a tool guaranteed delivery of messages. Unfortunately HermesEventBus is not suitable for this purpose. Hopefully in the future this tool will be debugged.
# 

08-08 19:23:45.610 15747-15772/ru.effortcounter W/System.err: xiaofei.library.hermes.util.HermesException
08-08 19:23:45.615 15747-15772/ru.effortcounter W/System.err:     at xiaofei.library.hermes.util.TypeCenter.getClassType(TypeCenter.java:145)
08-08 19:23:45.615 15747-15772/ru.effortcounter W/System.err:     at xiaofei.library.hermes.receiver.InstanceGettingReceiver.<init>(InstanceGettingReceiver.java:44)
08-08 19:23:45.615 15747-15772/ru.effortcounter W/System.err:     at xiaofei.library.hermes.receiver.ReceiverDesignator.getReceiver(ReceiverDesignator.java:35)
08-08 19:23:45.615 15747-15772/ru.effortcounter W/System.err:     at xiaofei.library.hermes.HermesService$1.send(HermesService.java:48)
08-08 19:23:45.615 15747-15772/ru.effortcounter W/System.err:     at xiaofei.library.hermes.internal.IHermesService$Stub.onTransact(IHermesService.java:70)
08-08 19:23:45.615 15747-15772/ru.effortcounter W/System.err:     at android.os.Binder.execTransact(Binder.java:367)
08-08 19:23:45.615 15747-15772/ru.effortcounter W/System.err:     at dalvik.system.NativeStart.run(Native Method)
08-08 19:23:45.990 16867-16898/ru.effortcounter.licence D/dalvikvm: VFY: replacing opcode 0x71 at 0x000a
08-08 19:23:45.995 16867-16898/ru.effortcounter.licence D/dalvikvm: VFY: replacing opcode 0x71 at 0x000a
08-08 19:23:46.005 16867-16867/ru.effortcounter.licence W/System.err: ------------ Log.e ------------
08-08 19:23:46.005 16867-16867/ru.effortcounter.licence W/System.err: Mika.UncaughtException
08-08 19:23:46.005 16867-16867/ru.effortcounter.licence W/System.err: Thread StackTrace: dalvik.system.VMStack.getThreadStackTrace(Native Method)
08-08 19:23:46.005 16867-16867/ru.effortcounter.licence W/System.err: java.lang.Thread.getStackTrace(Thread.java:591)
08-08 19:23:46.005 16867-16867/ru.effortcounter.licence W/System.err: com.github.nikolaymakhonin.logger.Log.handleUncaughtException(Log.java:279)
08-08 19:23:46.005 16867-16867/ru.effortcounter.licence W/System.err: com.github.nikolaymakhonin.logger.Log.lambda$static$0(Log.java:272)
08-08 19:23:46.005 16867-16867/ru.effortcounter.licence W/System.err: com.github.nikolaymakhonin.logger.Log.access$lambda$0(Log.java)
08-08 19:23:46.005 16867-16867/ru.effortcounter.licence W/System.err: com.github.nikolaymakhonin.logger.Log$$Lambda$1.uncaughtException(Unknown Source)
08-08 19:23:46.005 16867-16867/ru.effortcounter.licence W/System.err: com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:249)
08-08 19:23:46.005 16867-16867/ru.effortcounter.licence W/System.err: java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
08-08 19:23:46.005 16867-16867/ru.effortcounter.licence W/System.err: java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
08-08 19:23:46.005 16867-16867/ru.effortcounter.licence W/System.err: dalvik.system.NativeStart.main(Native Method)
08-08 19:23:46.010 16867-16867/ru.effortcounter.licence W/System.err: java.lang.NullPointerException
08-08 19:23:46.010 16867-16867/ru.effortcounter.licence W/System.err:     at xiaofei.library.hermeseventbus.HermesEventBus$1$1.call(HermesEventBus.java:102)
08-08 19:23:46.010 16867-16867/ru.effortcounter.licence W/System.err:     at xiaofei.library.hermeseventbus.HermesEventBus$1$1.call(HermesEventBus.java:99)
08-08 19:23:46.010 16867-16867/ru.effortcounter.licence W/System.err:     at xiaofei.library.concurrentutils.ObjectCanary$2.call(ObjectCanary.java:117)
08-08 19:23:46.010 16867-16867/ru.effortcounter.licence W/System.err:     at xiaofei.library.concurrentutils.ObjectCanary$2.call(ObjectCanary.java:114)
08-08 19:23:46.010 16867-16867/ru.effortcounter.licence W/System.err:     at xiaofei.library.concurrentutils.ObjectCanary.performFunctionUnderCondition(ObjectCanary.java:183)
08-08 19:23:46.010 16867-16867/ru.effortcounter.licence W/System.err:     at xiaofei.library.concurrentutils.ObjectCanary.action(ObjectCanary.java:114)
08-08 19:23:46.010 16867-16867/ru.effortcounter.licence W/System.err:     at xiaofei.library.concurrentutils.ObjectCanary.action(ObjectCanary.java:110)
08-08 19:23:46.010 16867-16867/ru.effortcounter.licence W/System.err:     at xiaofei.library.hermeseventbus.HermesEventBus$1.onHermesConnected(HermesEventBus.java:99)
08-08 19:23:46.010 16867-16867/ru.effortcounter.licence W/System.err:     at xiaofei.library.hermes.internal.Channel$HermesServiceConnection.onServiceConnected(Channel.java:283)
08-08 19:23:46.010 16867-16867/ru.effortcounter.licence W/System.err:     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1098)
08-08 19:23:46.010 16867-16867/ru.effortcounter.licence W/System.err:     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1115)
08-08 19:23:46.010 16867-16867/ru.effortcounter.licence W/System.err:     at android.os.Handler.handleCallback(Handler.java:615)
08-08 19:23:46.010 16867-16867/ru.effortcounter.licence W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:92)
08-08 19:23:46.010 16867-16867/ru.effortcounter.licence W/System.err:     at android.os.Looper.loop(Looper.java:137)
08-08 19:23:46.015 16867-16867/ru.effortcounter.licence W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:4947)
08-08 19:23:46.015 16867-16867/ru.effortcounter.licence W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
08-08 19:23:46.015 16867-16867/ru.effortcounter.licence W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
08-08 19:23:46.015 16867-16867/ru.effortcounter.licence W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
08-08 19:23:46.015 16867-16867/ru.effortcounter.licence W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
08-08 19:23:46.015 16867-16867/ru.effortcounter.licence W/System.err:     at dalvik.system.NativeStart.main(Native Method)
08-08 19:23:46.015 16867-16867/ru.effortcounter.licence W/System.err: java.lang.NullPointerException
08-08 19:23:46.015 16867-16867/ru.effortcounter.licence W/System.err:     at xiaofei.library.hermeseventbus.HermesEventBus$1$1.call(HermesEventBus.java:102)
08-08 19:23:46.015 16867-16867/ru.effortcounter.licence W/System.err:     at xiaofei.library.hermeseventbus.HermesEventBus$1$1.call(HermesEventBus.java:99)
08-08 19:23:46.020 16867-16867/ru.effortcounter.licence W/System.err:     at xiaofei.library.concurrentutils.ObjectCanary$2.call(ObjectCanary.java:117)
08-08 19:23:46.020 16867-16867/ru.effortcounter.licence W/System.err:     at xiaofei.library.concurrentutils.ObjectCanary$2.call(ObjectCanary.java:114)
08-08 19:23:46.020 16867-16867/ru.effortcounter.licence W/System.err:     at xiaofei.library.concurrentutils.ObjectCanary.performFunctionUnderCondition(ObjectCanary.java:183)
08-08 19:23:46.020 16867-16867/ru.effortcounter.licence W/System.err:     at xiaofei.library.concurrentutils.ObjectCanary.action(ObjectCanary.java:114)
08-08 19:23:46.020 16867-16867/ru.effortcounter.licence W/System.err:     at xiaofei.library.concurrentutils.ObjectCanary.action(ObjectCanary.java:110)
08-08 19:23:46.020 16867-16867/ru.effortcounter.licence W/System.err:     at xiaofei.library.hermeseventbus.HermesEventBus$1.onHermesConnected(HermesEventBus.java:99)
08-08 19:23:46.020 16867-16867/ru.effortcounter.licence W/System.err:     at xiaofei.library.hermes.internal.Channel$HermesServiceConnection.onServiceConnected(Channel.java:283)
08-08 19:23:46.020 16867-16867/ru.effortcounter.licence W/System.err:     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1098)
08-08 19:23:46.020 16867-16867/ru.effortcounter.licence W/System.err:     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1115)
08-08 19:23:46.020 16867-16867/ru.effortcounter.licence W/System.err:     at android.os.Handler.handleCallback(Handler.java:615)
08-08 19:23:46.025 16867-16867/ru.effortcounter.licence W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:92)
08-08 19:23:46.025 16867-16867/ru.effortcounter.licence W/System.err:     at android.os.Looper.loop(Looper.java:137)
08-08 19:23:46.025 16867-16867/ru.effortcounter.licence W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:4947)
08-08 19:23:46.025 16867-16867/ru.effortcounter.licence W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
08-08 19:23:46.025 16867-16867/ru.effortcounter.licence W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
08-08 19:23:46.025 16867-16867/ru.effortcounter.licence W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
08-08 19:23:46.025 16867-16867/ru.effortcounter.licence W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
08-08 19:23:46.025 16867-16867/ru.effortcounter.licence W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by Xiaofei-it** [comment]
The exception is thrown from Line 145 of TypeCenter in the Hermes library, caused by a failure of finding class. And maybe you will see a log which tells you which class is not found, but the log is not pasted here.
Do you add the @ClassId annotation on the class of the event you post? If so, you should register the event using Hermes.register() in both processes.
Also, how do you stop and restart the application? In Android, the application will not be stopped unless you or the system kills the process of the application. Maybe what you refer to is that you quit the app by pressing the back button or the home button. Would you please tell me what happens before the exception is thrown?
So, please provide me with more information and I can see whether it is a bug or not.
When it comes to the debugging tool you mentioned, I also think it is a little difficult to debug in the Hermes library. You can tell me what kind of debugging tool you want, how it should be or what features it should have.
By the way,  thank you so much for your feedback.
And according to your last feedback, I have removed the attributes in AndroidManifest.xml, but have not released it. You can see the change from GitHub. Please tell me whether it has solved the problem you encountered last time.
Thank you again!
